runtime: php55
api_version: 1

handlers:
  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$
    application_readable: true

  # Serve php scripts.
  - url: /
    script: index.php
    secure: always

  - url: /aboutus
    script: aboutus.php
    secure: always

  - url: /services
    script: services.php
    secure: always

  - url: /booking
    script: booking.php
    secure: always

  - url: /contact
    script: contact.php
    secure: always
